
import type { Cafe } from "./types";

export const cafes: Cafe[] = [
  {
    slug: "sidra-lavado",
    codigo: "011",
    nombre: "Sidra\nLavado",
    notas: ["tamarindo", "dulce de mango", "piña"],
    perfil: "moderno",
    tueste: 3,
    tuesteNombre: "Medio",
    origen: {
      pais: "Colombia",
      region: "Pitalito, Huila",
      finca: "Los Cedros",
      productor: "Oswaldo Toro",
      altura: 1800,
      variedad: "Sidra",
      proceso: "Lavado",
    },
    puntajeSCA: 90,
    metodos: ["filtrado"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 75000 },
      { gramos: 500, precio: 150000 },
    ],
    moliendas: ["Grano", "Espresso", "Drip", "Prensa"],
    fechaTueste: "10-08-2026",
    agtron: 65,
    preparacionRecomendada: "Drip",
    estado: "disponible",
    categoria: "snow",
    colorBloque: "#0A302B",
    imagenes: {
      bolsa: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1787785224/SIDRA_LAV_xonjfk.png",
      caficultor: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1787785222/Caficultor_sidra_papayo_rvgbd9.jpg",
      notas: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1787786424/Notas_sidra_swl4qw.jpg",
    },
  },
  {
    slug: "papayo-natural",
    codigo: "012",
    nombre: "Papayo\nNatural",
    notas: ["frambuesa", "arándanos", "vino blanco", "chocolate"],
    perfil: "moderno",
    tueste: 3,
    tuesteNombre: "Medio",
    origen: {
      pais: "Colombia",
      region: "Pitalito, Huila",
      finca: "Los Cedros",
      productor: "Oswaldo Toro",
      altura: 1800,
      variedad: "Papayo",
      proceso: "Natural",
    },
    puntajeSCA: 90,
    metodos: ["filtrado"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 75000 },
      { gramos: 500, precio: 150000 },
    ],
    moliendas: ["Grano", "Espresso", "Drip", "Prensa"],
    fechaTueste: "10-08-2026",
    agtron: 65,
    preparacionRecomendada: "Drip",
    estado: "disponible",
    categoria: "fire",
    colorBloque: "#072230",
    imagenes: {
      bolsa: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1787785224/PAPAYO_NAT_mbk9mq.png",
      caficultor: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1787785222/Caficultor_sidra_papayo_rvgbd9.jpg",
      notas: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1787786468/Notas_papayo_jy32jn.jpg",
    },
  },
  {
    slug: "ombligon-natural",
    codigo: "002",
    nombre: "Ombligón\nNatural",
    notas: ["lichi y durazno", "yogurt de melocotón", "manzanilla"],
    perfil: "moderno",
    tueste: 3,
    tuesteNombre: "Medio",
    origen: {
      pais: "Colombia",
      region: "Palestina, Huila",
      finca: "Villa Pastora",
      productor: "Familia Mora Ortega",
      altura: 1680,
      variedad: "Ombligón",
      proceso: "Natural",
    },
    puntajeSCA: 88,
    metodos: ["filtrado"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 70000 },
      { gramos: 500, precio: 140000 },
    ],
    moliendas: ["Grano", "Espresso", "Drip", "Prensa"],
    fechaTueste: "10-08-2026",
    agtron: 65,
    preparacionRecomendada: "Drip",
    estado: "disponible",
    categoria: "fire",
    colorBloque: "#000000",
    imagenes: {
      bolsa: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1787786897/OMBLIGON_NAT_lbdzfi.png",
      caficultor: "https://images.unsplash.com/photo-1613399421011-1e634fa4dacc?w=1200&q=80&auto=format&fit=crop",
      notas: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1787786431/Notas_ombligon_jxfojo.jpg",
    },
  },
  {
    slug: "castillo-tambo",
    codigo: "002",
    nombre: "Castillo\nTambo",
    notas: ["avellanas", "chocolate amargo", "nueces", "mandarina"],
    perfil: "tradicional",
    tueste: 3,
    tuesteNombre: "Medio",
    origen: {
      pais: "Colombia",
      region: "Palestina, Huila",
      finca: "—",
      productor: "Linarco Rodríguez",
      altura: 2000,
      variedad: "Castillo",
      proceso: "Semi Lavado",
    },
    puntajeSCA: 85,
    metodos: ["espresso", "filtrado", "prensa"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 40000 },
      { gramos: 500, precio: 80000 },
    ],
    moliendas: ["Grano", "Espresso", "Drip", "Prensa"],
    fechaTueste: "10-08-2026",
    agtron: 65,
    preparacionRecomendada: "Espresso | Drip | Prensa",
    estado: "disponible",
    categoria: "terra",
    colorBloque: "#072230",
    imagenes: {
      bolsa: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1788049078/CASTILO_LAV_d3tu7n.png",
      caficultor: "https://images.unsplash.com/photo-1613399421011-1e634fa4dacc?w=1200&q=80&auto=format&fit=crop",
      notas: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1787786722/Notas_Castillo_dfflmr.jpg",
    },
  },
  {
    slug: "java-natural",
    codigo: "010",
    nombre: "Java\nNatural",
    notas: ["frutos rojos", "chocolate blanco", "vino"],
    perfil: "moderno",
    tueste: 3,
    tuesteNombre: "Medio",
    origen: {
      pais: "Colombia",
      region: "Guayabal de Síquima, Cundinamarca",
      finca: "El Amanecer",
      productor: "—",
      altura: 1850,
      variedad: "Java",
      proceso: "Natural",
    },
    puntajeSCA: 88,
    metodos: ["filtrado"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 75000 },
      { gramos: 500, precio: 150000 },
    ],
    moliendas: ["Grano", "Espresso", "Drip", "Prensa"],
    fechaTueste: "10-08-2026",
    agtron: 65,
    preparacionRecomendada: "Drip",
    estado: "disponible",
    categoria: "snow",
    colorBloque: "#0A302B",
    imagenes: {
      bolsa: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1788049082/JAVA_NAT_z1fhss.png",
      caficultor: "https://images.unsplash.com/photo-1613399421011-1e634fa4dacc?w=1200&q=80&auto=format&fit=crop",
      notas: "https://res.cloudinary.com/dfkd8tzhs/image/upload/v1787786611/Notas_Java_es1mvg.jpg",
    },
  },
  /* {
    slug: "colombia-lavado",
    codigo: "013",
    nombre: "Colombia\nLavado",
    notas: ["panela", "cítricos", "caramelo"],
    perfil: "tradicional",
    tueste: 3,
    tuesteNombre: "Medio",
    origen: {
      pais: "Colombia",
      region: "Huila",
      finca: "Por definir",
      productor: "Por definir",
      altura: 1700,
      variedad: "Castillo",
      proceso: "Lavado",
    },
    puntajeSCA: 85,
    metodos: ["espresso", "filtrado"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 40000 },
      { gramos: 500, precio: 80000 },
    ],
    moliendas: ["Grano", "Espresso", "Drip", "Prensa"],
    fechaTueste: "11-08-2026",
    agtron: 75,
    preparacionRecomendada: "Prensa",
    estado: "nuevo",
    categoria: "sand",
    colorBloque: "#000000",
    imagenes: {
      bolsa: "https://images.unsplash.com/photo-1642437271884-fe1d3393eef9?w=1200&q=80&auto=format&fit=crop",
      caficultor: "https://images.unsplash.com/photo-1613399421011-1e634fa4dacc?w=1200&q=80&auto=format&fit=crop",
      notas: "https://images.unsplash.com/photo-1594002348772-bc0cb57ade8b?w=1200&q=80&auto=format&fit=crop",
    },
  }, */
];
