// TODO: contenido de ejemplo — reemplazar con datos reales del cliente
import type { Cafe } from "./types";

const espresso = (molienda = "Fina"): Cafe["preparacion"][number] => ({
  metodo: "Espresso",
  ratio: "1:2",
  molienda,
  temperatura: "93°C",
  tiempo: "28s",
});

const v60 = (): Cafe["preparacion"][number] => ({
  metodo: "V60",
  ratio: "1:15",
  molienda: "Media",
  temperatura: "93°C",
  tiempo: "2:45",
});

const prensa = (): Cafe["preparacion"][number] => ({
  metodo: "Prensa francesa",
  ratio: "1:12",
  molienda: "Gruesa",
  temperatura: "94°C",
  tiempo: "4:00",
});

export const cafes: Cafe[] = [
  {
    slug: "titan",
    codigo: "01",
    nombre: "TITAN",
    notas: ["Chocolate", "Panela", "Nuez"],
    perfil: "tradicional",
    tueste: 4,
    tuesteNombre: "Medio-oscuro",
    origen: {
      pais: "Colombia",
      region: "Huila",
      finca: "Finca La Esperanza",
      productor: "Asociación de Caficultores de Acevedo",
      altura: 1750,
      variedad: "Caturra",
      proceso: "Lavado",
    },
    puntajeSCA: 85,
    metodos: ["espresso", "prensa"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 32000 },
      { gramos: 340, precio: 42000 },
      { gramos: 1000, precio: 115000 },
    ],
    moliendas: ["Grano entero", "Espresso", "Prensa"],
    fechaTueste: "2026-08-11",
    estado: "disponible",
    colorBloque: "#000000",
    imagen: "/img/cafe/titan.jpg",
    preparacion: [espresso(), prensa()],
  },
  {
    slug: "darth-black",
    codigo: "02",
    nombre: "DARTH BLACK",
    notas: ["Cacao amargo", "Café tostado", "Regaliz"],
    perfil: "tradicional",
    tueste: 5,
    tuesteNombre: "Oscuro",
    origen: {
      pais: "Colombia",
      region: "Tolima",
      finca: "Finca El Placer",
      productor: "Cooperativa Cafetera del Tolima",
      altura: 1600,
      variedad: "Castillo",
      proceso: "Natural",
    },
    puntajeSCA: 84,
    metodos: ["espresso"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 30000 },
      { gramos: 340, precio: 40000 },
      { gramos: 1000, precio: 108000 },
    ],
    moliendas: ["Grano entero", "Espresso"],
    fechaTueste: "2026-08-11",
    estado: "disponible",
    colorBloque: "#072230",
    imagen: "/img/cafe/darth-black.jpg",
    preparacion: [espresso("Fina — extracción larga")],
  },
  {
    slug: "obsidiana",
    codigo: "03",
    nombre: "OBSIDIANA",
    notas: ["Mora", "Vino tinto", "Caramelo"],
    perfil: "moderno",
    tueste: 2,
    tuesteNombre: "Claro",
    origen: {
      pais: "Colombia",
      region: "Nariño",
      finca: "Finca Villa Loyola",
      productor: "Jhon Ortiz",
      altura: 1980,
      variedad: "Pink Bourbon",
      proceso: "Anaeróbico",
    },
    puntajeSCA: 88,
    metodos: ["filtrado"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 42000 },
      { gramos: 340, precio: 55000 },
    ],
    moliendas: ["Grano entero", "Filtrado"],
    fechaTueste: "2026-08-11",
    estado: "limitada",
    colorBloque: "#000000",
    imagen: "/img/cafe/obsidiana.jpg",
    preparacion: [v60()],
  },
  {
    slug: "altiplano",
    codigo: "04",
    nombre: "ALTIPLANO",
    notas: ["Manzana verde", "Miel", "Cítricos"],
    perfil: "moderno",
    tueste: 2,
    tuesteNombre: "Claro",
    origen: {
      pais: "Colombia",
      region: "Cauca",
      finca: "Finca Buenavista",
      productor: "Asociación ASPROCAFE Ínsula",
      altura: 1900,
      variedad: "Colombia",
      proceso: "Honey",
    },
    puntajeSCA: 87,
    metodos: ["filtrado", "coldbrew"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 36000 },
      { gramos: 340, precio: 47000 },
      { gramos: 1000, precio: 128000 },
    ],
    moliendas: ["Grano entero", "Filtrado", "Cold brew"],
    fechaTueste: "2026-08-11",
    estado: "disponible",
    colorBloque: "#0A302B",
    imagen: "/img/cafe/altiplano.jpg",
    preparacion: [v60()],
  },
  {
    slug: "crater",
    codigo: "05",
    nombre: "CRÁTER",
    notas: ["Almendra", "Chocolate con leche", "Ciruela"],
    perfil: "tradicional",
    tueste: 3,
    tuesteNombre: "Medio",
    origen: {
      pais: "Colombia",
      region: "Caldas",
      finca: "Finca La Cabaña",
      productor: "Comité de Cafeteros de Caldas",
      altura: 1700,
      variedad: "Castillo",
      proceso: "Lavado",
    },
    puntajeSCA: 85,
    metodos: ["espresso", "filtrado"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 30000 },
      { gramos: 340, precio: 39000 },
      { gramos: 1000, precio: 105000 },
    ],
    moliendas: ["Grano entero", "Espresso", "Filtrado"],
    fechaTueste: "2026-08-04",
    estado: "disponible",
    colorBloque: "#072230",
    imagen: "/img/cafe/crater.jpg",
    preparacion: [espresso(), v60()],
  },
  {
    slug: "nomada",
    codigo: "06",
    nombre: "NÓMADA",
    notas: ["Durazno", "Té negro", "Jazmín"],
    perfil: "moderno",
    tueste: 1,
    tuesteNombre: "Muy claro",
    origen: {
      pais: "Etiopía",
      region: "Yirgacheffe",
      finca: "Cooperativa Konga",
      productor: "Pequeños productores de Gedeo",
      altura: 2050,
      variedad: "Heirloom",
      proceso: "Lavado",
    },
    puntajeSCA: 89,
    metodos: ["filtrado"],
    descafeinado: false,
    presentaciones: [
      { gramos: 250, precio: 48000 },
      { gramos: 340, precio: 62000 },
    ],
    moliendas: ["Grano entero", "Filtrado"],
    fechaTueste: "2026-08-11",
    estado: "preventa",
    colorBloque: "#0A302B",
    imagen: "/img/cafe/nomada.jpg",
    preparacion: [v60()],
  },
  {
    slug: "solsticio",
    codigo: "07",
    nombre: "SOLSTICIO",
    notas: ["Panela", "Naranja", "Almendra tostada"],
    perfil: "tradicional",
    tueste: 3,
    tuesteNombre: "Medio",
    origen: {
      pais: "Colombia",
      region: "Quindío",
      finca: "Finca El Mirador",
      productor: "Comité de Cafeteros del Quindío",
      altura: 1650,
      variedad: "Typica",
      proceso: "Lavado",
    },
    puntajeSCA: 84,
    metodos: ["espresso", "prensa", "coldbrew"],
    descafeinado: true,
    presentaciones: [
      { gramos: 250, precio: 34000 },
      { gramos: 340, precio: 44000 },
      { gramos: 1000, precio: 118000 },
    ],
    moliendas: ["Grano entero", "Espresso", "Prensa"],
    fechaTueste: "2026-08-04",
    estado: "disponible",
    colorBloque: "#072230",
    imagen: "/img/cafe/solsticio.jpg",
    preparacion: [espresso(), prensa()],
  },
  {
    slug: "geisha-1750",
    codigo: "08",
    nombre: "GEISHA 1750",
    notas: ["Jazmín", "Bergamota", "Panela clara"],
    perfil: "moderno",
    tueste: 1,
    tuesteNombre: "Muy claro",
    origen: {
      pais: "Colombia",
      region: "Huila",
      finca: "Finca Villa Claudia",
      productor: "Diego Samuel Bermúdez",
      altura: 1750,
      variedad: "Geisha",
      proceso: "Lavado",
    },
    puntajeSCA: 91,
    metodos: ["filtrado"],
    descafeinado: false,
    presentaciones: [{ gramos: 250, precio: 68000 }],
    moliendas: ["Grano entero", "Filtrado"],
    fechaTueste: "2026-08-11",
    estado: "limitada",
    colorBloque: "#000000",
    imagen: "/img/cafe/geisha-1750.jpg",
    preparacion: [v60()],
  },
];
