
import type { MethodsShopItem } from "./types";

export const methodsShopItems: MethodsShopItem[] = [

  {
    slug: "hario-v60-dripper-02",
    nombre: "V60 Dripper 02",
    marca: "Hario",
    categoria: "drips",
    precio: 89000,
    imagen: "/img/methods-shop/hario-v60.jpg",
    descripcion: "El método que más usamos en la barra para filtrados de un solo origen.",
    stock: true,
  },
  {
    slug: "chemex-6-cup",
    nombre: "Chemex 6 tazas",
    marca: "Chemex",
    categoria: "drips",
    precio: 245000,
    imagen: "/img/methods-shop/chemex.jpg",
    descripcion: "Cuerpo entero, taza limpia. Lo recomendamos para perfiles claros.",
    stock: true,
  },
  {
    slug: "kalita-wave-155",
    nombre: "Wave 155",
    marca: "Kalita",
    categoria: "drips",
    precio: 165000,
    imagen: "/img/methods-shop/kalita-wave.jpg",
    descripcion: "Fondo plano, extracción más pareja. Bueno para empezar en filtrados.",
    stock: true,
  },
  {
    slug: "aeropress-original",
    nombre: "AeroPress Original",
    marca: "AeroPress",
    categoria: "drips",
    precio: 195000,
    imagen: "/img/methods-shop/aeropress.jpg",
    descripcion: "El que nos llevamos de viaje. Rápido y fácil de limpiar.",
    stock: true,
  },

  {
    slug: "comandante-c40-mk4",
    nombre: "C40 MK4",
    marca: "Comandante",
    categoria: "molinos",
    precio: 1450000,
    imagen: "/img/methods-shop/comandante-c40.jpg",
    descripcion: "Molino manual que usamos para catación y para la barra de filtrados.",
    stock: true,
  },
  {
    slug: "timemore-c2",
    nombre: "C2",
    marca: "Timemore",
    categoria: "molinos",
    precio: 320000,
    imagen: "/img/methods-shop/timemore-c2.jpg",
    descripcion: "Buena relación precio-consistencia para empezar en casa.",
    stock: true,
  },
  {
    slug: "baratza-encore",
    nombre: "Encore",
    marca: "Baratza",
    categoria: "molinos",
    precio: 890000,
    imagen: "/img/methods-shop/baratza-encore.jpg",
    descripcion: "Eléctrico, el que recomendamos para uso diario en casa.",
    stock: true,
  },
  {
    slug: "1zpresso-j-max",
    nombre: "J-Max",
    marca: "1Zpresso",
    categoria: "molinos",
    precio: 780000,
    imagen: "/img/methods-shop/1zpresso-jmax.jpg",
    descripcion: "Manual, muela cónica. Lo usamos para espresso en casa.",
    stock: false,
  },

  {
    slug: "taza-espresso-90ml",
    nombre: "Taza espresso 90 ml",
    marca: "Espresso Coffee Shop",
    categoria: "tazas",
    precio: 45000,
    imagen: "/img/methods-shop/taza-espresso.jpg",
    descripcion: "La misma que usamos en la barra. Cerámica, pared gruesa.",
    stock: true,
  },
  {
    slug: "taza-ceramica-300ml",
    nombre: "Taza cerámica 300 ml",
    marca: "Espresso Coffee Shop",
    categoria: "tazas",
    precio: 52000,
    imagen: "/img/methods-shop/taza-ceramica.jpg",
    descripcion: "Para filtrados y métodos. Sella calor mejor que el vidrio.",
    stock: true,
  },
  {
    slug: "vaso-cold-brew-400ml",
    nombre: "Vaso cold brew 400 ml",
    marca: "Espresso Coffee Shop",
    categoria: "tazas",
    precio: 38000,
    imagen: "/img/methods-shop/vaso-cold-brew.jpg",
    descripcion: "Vidrio grueso, doble pared. El de la barra en verano.",
    stock: true,
  },
  {
    slug: "set-tazas-filtrado-x2",
    nombre: "Set x2 tazas filtrado",
    marca: "Espresso Coffee Shop",
    categoria: "tazas",
    precio: 85000,
    imagen: "/img/methods-shop/set-tazas-filtrado.jpg",
    descripcion: "Para catar en casa como catamos en la barra.",
    stock: true,
  },

  {
    slug: "timemore-black-mirror",
    nombre: "Black Mirror Basic",
    marca: "Timemore",
    categoria: "accesorios",
    precio: 340000,
    imagen: "/img/methods-shop/timemore-bascula.jpg",
    descripcion: "Báscula con temporizador. La usamos en cada método de la barra.",
    stock: true,
  },
  {
    slug: "fellow-stagg-ekg",
    nombre: "Stagg EKG",
    marca: "Fellow",
    categoria: "accesorios",
    precio: 680000,
    imagen: "/img/methods-shop/fellow-stagg.jpg",
    descripcion: "Hervidor de cuello de ganso con control de temperatura.",
    stock: true,
  },
  {
    slug: "filtros-v60-x100",
    nombre: "Filtros V60 blancos x100",
    marca: "Hario",
    categoria: "accesorios",
    precio: 28000,
    imagen: "/img/methods-shop/filtros-v60.jpg",
    descripcion: "Los mismos que usamos en la barra para el V60.",
    stock: true,
  },
  {
    slug: "jarra-vidrio-600ml",
    nombre: "Jarra de vidrio 600 ml",
    marca: "Hario",
    categoria: "accesorios",
    precio: 62000,
    imagen: "/img/methods-shop/jarra-vidrio.jpg",
    descripcion: "Para servir filtrados en mesa. Marcas de volumen grabadas.",
    stock: true,
  },
];
